"""
Vercel Serverless API — 纯 API 路由（不处理静态文件）
"""
import os
import json
import time
import threading
import urllib.request
import urllib.error

from flask import Flask, request, jsonify

app = Flask(__name__)
DASHSCOPE_API_KEY = os.getenv('DASHSCOPE_API_KEY', '')

# Rate limit
rate_limit_store = {}
rate_limit_lock = threading.Lock()

def check_rate_limit(ip):
    now = time.time()
    with rate_limit_lock:
        if ip in rate_limit_store:
            elapsed = now - rate_limit_store[ip]
            if elapsed < 10:
                return False, int(10 - elapsed)
        rate_limit_store[ip] = now
        expired = [k for k, v in rate_limit_store.items() if now - v > 60]
        for k in expired: del rate_limit_store[k]
        return True, 0

FALLBACK = '''【时刻互联，智在腕间】
全新 X-Watch Pro 搭载 AI 智能助手。
7x24 心率血氧双监测 | eSIM 独立通话 | 14天超长续航。
这一刻，与世界同频。'''

ART_FALLBACK = '（图片生成演示）科技感海报：深蓝渐变背景，悬浮产品图，环绕发光科技线条。配置 API Key 后启用真实图片生成。'

def call_qwen_text(prompt):
    url = 'https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions'
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Bearer {DASHSCOPE_API_KEY}'
    }
    body = {
        'model': 'qwen-max',
        'messages': [
            {'role': 'system', 'content': '你是「一人公司」的超级员工，回复简洁专业。'},
            {'role': 'user', 'content': prompt}
        ],
        'temperature': 0.8,
        'max_tokens': 2000
    }
    req = urllib.request.Request(url, data=json.dumps(body).encode('utf-8'), headers=headers, method='POST')
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.loads(resp.read().decode('utf-8'))
        return data['choices'][0]['message']['content']

def call_wanx_image(prompt):
    submit_url = 'https://dashscope.aliyuncs.com/api/v1/services/aigc/text2image/image-synthesis'
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Bearer {DASHSCOPE_API_KEY}',
        'X-DashScope-Async': 'enable'
    }
    body = {'model': 'wanx2.1-t2i-turbo', 'input': {'prompt': prompt}, 'parameters': {'size': '1024*1024', 'n': 1}}
    req = urllib.request.Request(submit_url, data=json.dumps(body).encode('utf-8'), headers=headers, method='POST')
    with urllib.request.urlopen(req, timeout=15) as resp:
        data = json.loads(resp.read().decode('utf-8'))
        task_id = data.get('output', {}).get('task_id')
        if not task_id: raise Exception('No task_id')

    for _ in range(20):
        time.sleep(3)
        req2 = urllib.request.Request(
            f'https://dashscope.aliyuncs.com/api/v1/tasks/{task_id}',
            headers={'Authorization': f'Bearer {DASHSCOPE_API_KEY}'}
        )
        with urllib.request.urlopen(req2, timeout=10) as resp:
            data = json.loads(resp.read().decode('utf-8'))
            status = data.get('output', {}).get('task_status')
            if status == 'SUCCEEDED':
                url = data.get('output', {}).get('results', [{}])[0].get('url')
                if url: return url
            if status == 'FAILED': raise Exception('Task failed')
    raise Exception('Timeout')

@app.route('/api/health')
def health():
    return jsonify({
        'status': 'ok',
        'apiKeyConfigured': bool(DASHSCOPE_API_KEY),
        'mode': 'production' if DASHSCOPE_API_KEY else 'demo'
    })

@app.route('/api/generate-text', methods=['POST'])
def generate_text():
    ip = request.headers.get('x-forwarded-for', request.remote_addr or 'unknown')
    allowed, remaining = check_rate_limit(ip)
    if not allowed:
        return jsonify({'success': False, 'error': f'Rate limit, {remaining}s', 'fallback': True}), 429

    data = request.get_json(silent=True) or {}
    prompt = (data.get('prompt') or '').strip()
    if not prompt:
        return jsonify({'success': False, 'error': 'Prompt required'}), 400

    if not DASHSCOPE_API_KEY:
        return jsonify({'success': True, 'content': FALLBACK, 'tag': 'Demo mode - add DASHSCOPE_API_KEY env var', 'fallback': True})

    try:
        result = call_qwen_text(prompt)
        return jsonify({'success': True, 'content': result, 'tag': 'Generated by Qianwen', 'fallback': False})
    except Exception as e:
        return jsonify({'success': True, 'content': FALLBACK, 'tag': 'Fallback (API error)', 'fallback': True, 'error': str(e)})

@app.route('/api/generate-image', methods=['POST'])
def generate_image():
    ip = request.headers.get('x-forwarded-for', request.remote_addr or 'unknown')
    allowed, remaining = check_rate_limit(ip)
    if not allowed:
        return jsonify({'success': False, 'error': f'Rate limit, {remaining}s', 'fallback': True}), 429

    data = request.get_json(silent=True) or {}
    prompt = (data.get('prompt') or '').strip()
    if not prompt:
        return jsonify({'success': False, 'error': 'Prompt required'}), 400

    if not DASHSCOPE_API_KEY:
        return jsonify({'success': True, 'fallback': True, 'description': ART_FALLBACK, 'tag': 'Demo mode'})

    try:
        image_url = call_wanx_image(prompt)
        return jsonify({'success': True, 'imageUrl': image_url, 'tag': 'Generated by Qianwen', 'fallback': False})
    except Exception as e:
        return jsonify({'success': True, 'fallback': True, 'description': ART_FALLBACK, 'tag': 'Fallback', 'error': str(e)})
